AudioInputI2S            i2s1;           
AudioEffectFreeverb      freeverb1;      
AudioEffectFreeverb      freeverb2;      
AudioFilterBiquad        biquad2;        
AudioFilterBiquad        biquad1;        
AudioMixer4              mixer1;         
AudioAnalyzeFFT1024      fft1024;      
AudioOutputI2S           i2s2;           
AudioConnection          patchCord1(i2s1, 0, freeverb1, 0);
AudioConnection          patchCord2(i2s1, 0, mixer1, 2);
AudioConnection          patchCord3(i2s1, 1, freeverb2, 0);
AudioConnection          patchCord4(i2s1, 1, mixer1, 3);
AudioConnection          patchCord5(freeverb1, biquad1);
AudioConnection          patchCord6(freeverb2, biquad2);
AudioConnection          patchCord7(biquad1, 0, mixer1, 1);
AudioConnection          patchCord8(biquad2, 0, mixer1, 0);
AudioConnection          patchCord9(mixer1, fft1024);
AudioConnection          patchCord10(mixer1, 0, i2s2, 0);
AudioConnection          patchCord11(mixer1, 0, i2s2, 1);
AudioControlSGTL5000     sgtl5000_1;     

